# Generated by Django 4.2.3 on 2023-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='afiliacao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='canal_do_youtube',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='caracteristica_produto',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='caracteristicas_pagina_hotmart',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='produto',
            name='comissao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='conquista',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='grau_do_produto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_do_produto',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_produto',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='moeda',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nota_do_produto',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='numero_de_avaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pagina_do_produto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='porcentagem_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
