# Generated by Django 4.2.3 on 2023-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_afiliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='afiliacao',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='canal_do_youtube',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='caracteristica_produto',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='caracteristicas_pagina_hotmart',
            field=models.TextField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='comissao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='conquista',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_produto',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='moeda',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pagina_do_produto',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='porcentagem_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
