# Generated by Django 4.2.3 on 2023-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_categoria_produto_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='avaliacao_do_produto',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='inscritos_youtube',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='video_de_venda',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
