# Generated by Django 4.2.3 on 2023-07-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_avaliacao_do_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='inscritos_youtube',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
