# Generated by Django 4.2.3 on 2023-07-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_produto_url_do_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='id_do_produto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
