# Generated by Django 4.2.3 on 2023-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_produto_id_do_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qualidadedoproduto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
