# Generated by Django 4.2.3 on 2023-07-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produto_url_do_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='link_checkout',
            field=models.CharField(default='', max_length=200),
        ),
    ]
