# Generated by Django 4.2.3 on 2023-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_produto_link_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='link_youtube',
            field=models.CharField(default='', max_length=200),
        ),
    ]
