# Generated by Django 4.2.3 on 2023-07-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_alter_produto_link_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_do_produto',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_checkout',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_youtube',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qualidadedoproduto',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='url_do_site',
            field=models.CharField(default='', max_length=400, null=True),
        ),
    ]
