# Generated by Django 4.2.3 on 2023-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_alter_produto_id_do_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='', max_length=300),
        ),
    ]
