# Generated by Django 4.2.3 on 2023-08-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_produto_quant_inscritos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='porcentagem_de_comissao',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
