# Generated by Django 4.2.3 on 2023-08-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_produto_porcentagem_de_comissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='porcentagem_comissao',
        ),
    ]
