# Generated by Django 4.2.3 on 2023-08-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_remove_produto_porcentagem_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_produto',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
    ]
