# Generated by Django 4.2.3 on 2023-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_produto_descricao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='verificacao',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
