# Generated by Django 4.2.3 on 2023-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_produto_verificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='atualizado',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_checkout',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
