# Generated by Django 4.2.3 on 2023-09-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_produto_atualizado_alter_produto_link_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='link_checkout',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qualidadedoproduto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='verificacao',
        ),
    ]
