# Generated by Django 4.2.3 on 2023-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0024_remove_produto_atualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=300)),
                ('dados', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
