# Generated by Django 4.2.3 on 2023-07-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem_do_produto', models.ImageField(upload_to='')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota_do_produto', models.DecimalField(decimal_places=1, max_digits=2)),
                ('grau_do_produto', models.IntegerField()),
                ('numero_de_avaliacoes', models.IntegerField()),
                ('moeda', models.CharField(max_length=5)),
                ('comissao', models.IntegerField()),
                ('porcentagem_comissao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('link_produto', models.TextField(max_length=500)),
                ('conquista', models.TextField(max_length=1000)),
                ('pagina_do_produto', models.CharField(max_length=100)),
                ('afiliacao', models.CharField(max_length=100)),
                ('caracteristicas_pagina_hotmart', models.TextField(max_length=300)),
                ('caracteristica_produto', models.TextField(max_length=1000)),
                ('canal_do_youtube', models.CharField(max_length=100)),
            ],
        ),
    ]
